CREATE TABLE employees
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_number VARCHAR(20)  NOT NULL,
    first_name      VARCHAR(100) NOT NULL,
    last_name       VARCHAR(100) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    phone_number    VARCHAR(30),
    job_title       VARCHAR(150) NOT NULL,
    department      VARCHAR(100) NOT NULL,
    hire_date       DATE         NOT NULL,
    status          VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_employees_employee_number
        UNIQUE (employee_number),

    CONSTRAINT ck_employees_status
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'ON_LEAVE', 'TERMINATED'))
);

CREATE UNIQUE INDEX uk_employees_email_lower
    ON employees (LOWER(email));